name: 🚀 Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 🚀 Deploy to VPS

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v2

      - name: 📧 Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: '.'
          target: '/var/www/vhosts/authentication-app'
